# Generated by Django 2.2.5 on 2019-10-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apartment_buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120, verbose_name='Location')),
                ('date', models.DateTimeField(verbose_name='Post Date')),
                ('venue', models.CharField(max_length=120)),
                ('person', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='apartment_sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120, verbose_name='Location')),
                ('date', models.DateTimeField(verbose_name='Post Date')),
                ('venue', models.CharField(max_length=120)),
                ('person', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='rent_buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120, verbose_name='Location')),
                ('date', models.DateTimeField(verbose_name='Post Date')),
                ('venue', models.CharField(max_length=120)),
                ('person', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='rent_sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120, verbose_name='Location')),
                ('date', models.DateTimeField(verbose_name='Post Date')),
                ('venue', models.CharField(max_length=120)),
                ('person', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
